# Materializes the reviewed Codex config and rules inputs into generated files.
#
# Authorship contract (YZXCONV-004):
#   editable input : ~/.config/yazelix/agents/codex/config.toml.src (deploy surface)
#   review copy    : agent_configs/codex/config.toml.src (this repo)
#   rules input    : ~/.config/yazelix/agents/codex/RULES.md.src
#   rules review   : agent_configs/codex/RULES.md.src
#   generated out  : $CODEX_HOME/config.toml and $CODEX_HOME/RULES.md — staged
#                    together and atomically replaced from their shared directory
#
# The runtime/state home stays CODEX_HOME=/home/flexnetos/.codex; auth.json,
# sessions/, and *.sqlite* are runtime state and are never touched here.
#
# Fail-closed validation: the input must be valid TOML and must not reference
# the retired /home/flexnetos/FlexNetOS workspace mirror, raw /nix/store pins,
# Nix profile-generation paths, or user-local binaries — ~/.nix-profile is the
# sole binary selector.

const CONFIG_GENERATED_MARKER = "GENERATED by yazelix codex config materializer"
const RULES_GENERATED_MARKER = "GENERATED by yazelix codex rules materializer"
const CANONICAL_CONFIG_INPUT = "~/.config/yazelix/agents/codex/config.toml.src"
const CANONICAL_RULES_INPUT = "~/.config/yazelix/agents/codex/RULES.md.src"
const FORBIDDEN_PATHS = [
    "/home/flexnetos/FlexNetOS"            # retired workspace mirror
    "/nix/store/"                          # raw store pin bypasses the profile selector
    "/nix/var/nix/profiles/"               # system profile-generation pin
    ".local/state/nix/profiles/profile-"   # user profile-generation pin
    "/home/flexnetos/.local/bin/"           # stale user-local executable shadow
]

def fail [message: string] {
    print --stderr $"codex config materializer: ($message)"
    exit 1
}

def remove-if-present [target: path] {
    if ($target | path exists) {
        rm --force $target
    }
}

def main [config_src: path, config_out: path, rules_src: path, rules_out: path] {
    if not ($config_src | path exists) {
        fail $"config input not found: ($config_src)"
    }
    if not ($rules_src | path exists) {
        fail $"rules input not found: ($rules_src)"
    }

    let config_raw = (open --raw $config_src)
    try { $config_raw | from toml | ignore } catch {
        fail $"config input is not valid TOML: ($config_src)"
    }
    for pattern in $FORBIDDEN_PATHS {
        if ($config_raw | str contains $pattern) {
            fail $"config input references forbidden path ($pattern): ($config_src)"
        }
    }

    let rules_raw = (open --raw $rules_src)
    if not ($rules_raw | str starts-with "# FlexNetOS Codex Durable Rules\n") {
        fail $"rules input must start with the durable rules heading: ($rules_src)"
    }
    if ($rules_raw | str contains $RULES_GENERATED_MARKER) {
        fail $"rules input contains a generated-output marker: ($rules_src)"
    }

    let config_hash = ($config_raw | hash sha256)
    let rules_hash = ($rules_raw | hash sha256)
    let config_header = [
        $"# ($CONFIG_GENERATED_MARKER) — do not hand-edit."
        $"# authorship input: ($CANONICAL_CONFIG_INPUT)"
        $"# source_sha256 = ($config_hash)"
        ""
    ]
    let rules_header = [
        $"<!-- ($RULES_GENERATED_MARKER) — do not hand-edit. -->"
        $"<!-- authorship input: ($CANONICAL_RULES_INPUT) -->"
        $"<!-- source_sha256 = ($rules_hash) -->"
        ""
    ]

    if $config_out == $rules_out {
        fail "config and rules outputs must be different files"
    }
    for output in [$config_out $rules_out] {
        if ($output | path exists) and (($output | path type) == "dir") {
            fail $"output path is a directory: ($output)"
        }
    }

    let config_dir = ($config_out | path dirname | path expand)
    let rules_dir = ($rules_out | path dirname | path expand)
    if $config_dir != $rules_dir {
        fail "config and rules outputs must share one directory for transactional replacement"
    }
    mkdir $config_dir

    let token = (random uuid)
    let config_stage = ($config_dir | path join $".config.toml.yazelix-stage-($token)")
    let rules_stage = ($config_dir | path join $".RULES.md.yazelix-stage-($token)")
    let config_backup = ($config_dir | path join $".config.toml.yazelix-backup-($token)")
    let rules_backup = ($config_dir | path join $".RULES.md.yazelix-backup-($token)")
    let config_rendered = (($config_header | str join "\n") + $config_raw)
    let rules_rendered = (($rules_header | str join "\n") + $rules_raw)

    # Prepare both complete files before changing either live output. A staging
    # failure therefore leaves the previous generation byte-for-byte intact.
    try {
        $config_rendered | save --raw $config_stage
        $rules_rendered | save --raw $rules_stage
    } catch {|error|
        remove-if-present $config_stage
        remove-if-present $rules_stage
        fail $"unable to stage output pair: ($error.msg)"
    }
    for staged in [$config_stage $rules_stage] {
        let mode = (do { ^chmod 0644 $staged } | complete)
        if $mode.exit_code != 0 {
            remove-if-present $config_stage
            remove-if-present $rules_stage
            fail $"unable to set generated output mode 0644: ($staged)"
        }
    }

    let had_config = ($config_out | path exists)
    let had_rules = ($rules_out | path exists)
    try {
        if $had_config { cp $config_out $config_backup }
        if $had_rules { cp $rules_out $rules_backup }
    } catch {|error|
        remove-if-present $config_stage
        remove-if-present $rules_stage
        remove-if-present $config_backup
        remove-if-present $rules_backup
        fail $"unable to stage rollback copies: ($error.msg)"
    }

    try {
        mv --force $config_stage $config_out
    } catch {|error|
        remove-if-present $config_stage
        remove-if-present $rules_stage
        remove-if-present $config_backup
        remove-if-present $rules_backup
        fail $"unable to replace config output: ($error.msg)"
    }
    try {
        mv --force $rules_stage $rules_out
    } catch {|error|
        if $had_config {
            mv --force $config_backup $config_out
        } else {
            remove-if-present $config_out
        }
        remove-if-present $rules_stage
        remove-if-present $config_backup
        remove-if-present $rules_backup
        fail $"unable to replace rules output; config was rolled back: ($error.msg)"
    }
    remove-if-present $config_backup
    remove-if-present $rules_backup

    print $"ok materialized ($config_out) source_sha256=($config_hash)"
    print $"ok materialized ($rules_out) source_sha256=($rules_hash)"
}
