# Materializes the reviewed Codex config and rules inputs into generated files.
#
# Authorship contract (YZXCONV-004):
#   editable input : ~/.config/yazelix/agents/codex/config.toml.src (deploy surface)
#   review copy    : agent_configs/codex/config.toml.src (this repo)
#   rules input    : ~/.config/yazelix/agents/codex/RULES.md.src
#   rules review   : agent_configs/codex/RULES.md.src
#   generated out  : $CODEX_HOME/config.toml and $CODEX_HOME/RULES.md — only
#                    written together after both inputs validate, at an approved
#                    cutover with a checksum-backed backup of the prior file
#
# The runtime/state home stays CODEX_HOME=/home/flexnetos/.codex; auth.json,
# sessions/, and *.sqlite* are runtime state and are never touched here.
#
# Fail-closed validation: the input must be valid TOML and must not reference
# the retired /home/flexnetos/FlexNetOS workspace mirror, raw /nix/store pins,
# or Nix profile-generation paths — ~/.nix-profile is the sole binary selector.

const CONFIG_GENERATED_MARKER = "GENERATED by yazelix codex config materializer"
const RULES_GENERATED_MARKER = "GENERATED by yazelix codex rules materializer"
const CANONICAL_CONFIG_INPUT = "~/.config/yazelix/agents/codex/config.toml.src"
const CANONICAL_RULES_INPUT = "~/.config/yazelix/agents/codex/RULES.md.src"
const FORBIDDEN_PATHS = [
    "/home/flexnetos/FlexNetOS"            # retired workspace mirror
    "/nix/store/"                          # raw store pin bypasses the profile selector
    "/nix/var/nix/profiles/"               # system profile-generation pin
    ".local/state/nix/profiles/profile-"   # user profile-generation pin
]

def fail [message: string] {
    print --stderr $"codex config materializer: ($message)"
    exit 1
}

def main [config_src: path, config_out: path, rules_src: path, rules_out: path] {
    if not ($config_src | path exists) {
        fail $"config input not found: ($config_src)"
    }
    if not ($rules_src | path exists) {
        fail $"rules input not found: ($rules_src)"
    }

    let config_raw = (open --raw $config_src)
    try { $config_raw | from toml | ignore } catch {
        fail $"config input is not valid TOML: ($config_src)"
    }
    for pattern in $FORBIDDEN_PATHS {
        if ($config_raw | str contains $pattern) {
            fail $"config input references forbidden path ($pattern): ($config_src)"
        }
    }

    let rules_raw = (open --raw $rules_src)
    if not ($rules_raw | str starts-with "# FlexNetOS Codex Durable Rules\n") {
        fail $"rules input must start with the durable rules heading: ($rules_src)"
    }
    if ($rules_raw | str contains $RULES_GENERATED_MARKER) {
        fail $"rules input contains a generated-output marker: ($rules_src)"
    }

    let config_hash = ($config_raw | hash sha256)
    let rules_hash = ($rules_raw | hash sha256)
    let config_header = [
        $"# ($CONFIG_GENERATED_MARKER) — do not hand-edit."
        $"# authorship input: ($CANONICAL_CONFIG_INPUT)"
        $"# source_sha256 = ($config_hash)"
        ""
    ]
    let rules_header = [
        $"<!-- ($RULES_GENERATED_MARKER) — do not hand-edit. -->"
        $"<!-- authorship input: ($CANONICAL_RULES_INPUT) -->"
        $"<!-- source_sha256 = ($rules_hash) -->"
        ""
    ]

    # Both inputs are loaded and validated before either output is changed.
    mkdir ($config_out | path dirname)
    mkdir ($rules_out | path dirname)
    (($config_header | str join "\n") + $config_raw) | save --force --raw $config_out
    (($rules_header | str join "\n") + $rules_raw) | save --force --raw $rules_out
    print $"ok materialized ($config_out) source_sha256=($config_hash)"
    print $"ok materialized ($rules_out) source_sha256=($rules_hash)"
}
