# Materializes the reviewed Codex config, rules, and hooks inputs.
#
# Authorship contract (YZXCONV-004):
#   reviewed input : agent_configs/codex/config.toml.src (this repo)
#   installed input: profile share/yazelix/agent_configs/codex/config.toml.src
#   rules review   : agent_configs/codex/RULES.md.src (this repo)
#   installed rules: profile share/yazelix/agent_configs/codex/RULES.md.src
#   hooks review   : agent_configs/codex/hooks.json.src (this repo)
#   installed hooks: profile share/yazelix/agent_configs/codex/hooks.json.src
#   generated out  : $CODEX_HOME/config.toml, $CODEX_HOME/RULES.md, and
#                    $CODEX_HOME/hooks.json — all completed before
#                    rollback-assisted publication
#
# The profile-owned launcher fixes CODEX_HOME to the profile runtime link.
# Auth, sessions, and databases remain runtime state and are never authored here.
#
# Fail-closed validation: the input must be valid TOML and must not reference
# the retired /home/flexnetos/FlexNetOS workspace mirror, raw /nix/store pins,
# Nix profile-generation paths, or home-root binary shadows — ~/.nix-profile is the
# sole binary selector.

const CONFIG_GENERATED_MARKER = "GENERATED by yazelix codex config materializer"
const RULES_GENERATED_MARKER = "GENERATED by yazelix codex rules materializer"
const HOOKS_GENERATED_MARKER = "GENERATED by yazelix codex hooks materializer"
const CANONICAL_CONFIG_INPUT = "/home/flexnetos/.nix-profile/share/yazelix/agent_configs/codex/config.toml.src"
const CANONICAL_RULES_INPUT = "/home/flexnetos/.nix-profile/share/yazelix/agent_configs/codex/RULES.md.src"
const CANONICAL_HOOKS_INPUT = "/home/flexnetos/.nix-profile/share/yazelix/agent_configs/codex/hooks.json.src"
const LEGACY_TRANSACTION_SCHEMA = "yazelix.codex-config-transaction.v1"
const TRANSACTION_SCHEMA = "yazelix.codex-config-transaction.v2"
const TRANSACTION_JOURNAL = ".yazelix-codex-transaction.json"
const PROFILE_ICM = "/home/flexnetos/.nix-profile/bin/icm"
const OWNED_HOOK_COMMANDS = [
    "/home/flexnetos/.nix-profile/bin/icm hook start"
    "/home/flexnetos/.nix-profile/bin/rtk hook codex"
    "/home/flexnetos/.nix-profile/bin/icm hook pre"
    "/home/flexnetos/.nix-profile/bin/icm hook compact"
    "/home/flexnetos/.nix-profile/bin/icm hook prompt"
    "/home/flexnetos/.nix-profile/bin/icm hook end"
]
const PRESERVED_OPTIONAL_HOOK_COMMANDS = [
    "/home/flexnetos/.nix-profile/bin/icm hook post"
]
const REQUIRED_HOOKS = {
    SessionStart: [{hooks: [{type: "command", command: "/home/flexnetos/.nix-profile/bin/icm hook start"}]}]
    PreToolUse: [{matcher: "^Bash$", hooks: [
        {type: "command", command: "/home/flexnetos/.nix-profile/bin/rtk hook codex"}
        {type: "command", command: "/home/flexnetos/.nix-profile/bin/icm hook pre"}
    ]}]
    PreCompact: [{hooks: [{type: "command", command: "/home/flexnetos/.nix-profile/bin/icm hook compact"}]}]
    UserPromptSubmit: [{hooks: [{type: "command", command: "/home/flexnetos/.nix-profile/bin/icm hook prompt"}]}]
    Stop: [{hooks: [{type: "command", command: "/home/flexnetos/.nix-profile/bin/icm hook end"}]}]
}
const FORBIDDEN_PATHS = [
    "/home/flexnetos/FlexNetOS"            # retired workspace mirror
    "/nix/store/"                          # raw store pin bypasses the profile selector
    "/nix/var/nix/profiles/"               # system profile-generation pin
]

def fail [message: string] {
    print --stderr $"codex config materializer: ($message)"
    exit 1
}

def remove-if-present [target: path] {
    if ($target | path exists) {
        rm --force $target
    }
}

def transaction-paths [directory: path, token: string] {
    {
        config_stage: ($directory | path join $".config.toml.yazelix-stage-($token)")
        rules_stage: ($directory | path join $".RULES.md.yazelix-stage-($token)")
        hooks_stage: ($directory | path join $".hooks.json.yazelix-stage-($token)")
        config_backup: ($directory | path join $".config.toml.yazelix-backup-($token)")
        rules_backup: ($directory | path join $".RULES.md.yazelix-backup-($token)")
        hooks_backup: ($directory | path join $".hooks.json.yazelix-backup-($token)")
    }
}

def transaction-artifacts [paths] {
    [
        $paths.config_stage
        $paths.rules_stage
        $paths.hooks_stage
        $paths.config_backup
        $paths.rules_backup
        $paths.hooks_backup
    ]
}

def remove-transaction-artifacts [paths] {
    for artifact in (transaction-artifacts $paths) {
        remove-if-present $artifact
    }
}

def restore-output [had_output: bool, backup: path, output: path] {
    if $had_output {
        if ($backup | path exists) {
            mv --force $backup $output
        }
    } else {
        remove-if-present $output
    }
}

def recover-transaction [journal: path, config_out: path, rules_out: path, hooks_out: path] {
    if not ($journal | path exists) { return false }
    let transaction = (try { open --raw $journal | from json } catch {
        fail $"pending transaction journal is invalid: ($journal)"
    })
    let directory = ($config_out | path dirname | path expand)
    let schema = ($transaction.schema? | default "")
    let legacy = $schema == $LEGACY_TRANSACTION_SCHEMA
    let current = $schema == $TRANSACTION_SCHEMA
    let common_valid = (
        ($legacy or $current)
        and ($transaction.token? | default "") =~ '^[0-9a-f-]+$'
        and ($transaction.config_name? | default "") == ($config_out | path basename)
        and ($transaction.rules_name? | default "") == ($rules_out | path basename)
        and (($transaction.had_config? | describe) == "bool")
        and (($transaction.had_rules? | describe) == "bool")
    )
    let hooks_valid = (
        $legacy or (
            ($transaction.hooks_name? | default "") == ($hooks_out | path basename)
            and (($transaction.had_hooks? | describe) == "bool")
        )
    )
    if not ($common_valid and $hooks_valid) {
        fail $"pending transaction journal does not match requested outputs: ($journal)"
    }
    let paths = (transaction-paths $directory $transaction.token)
    restore-output $transaction.had_config $paths.config_backup $config_out
    restore-output $transaction.had_rules $paths.rules_backup $rules_out
    if $current {
        restore-output $transaction.had_hooks $paths.hooks_backup $hooks_out
    }
    remove-transaction-artifacts $paths
    remove-if-present $journal
    do { ^sync -f $directory } | complete | ignore
    print $"recovered prior Codex config/rules/hooks generation from ($journal)"
    true
}

def is-record [value] {
    ($value | describe | str starts-with "record")
}

def is-list [value] {
    let type = ($value | describe)
    ($type | str starts-with "list") or ($type | str starts-with "table")
}

def validate-hook-document [document, label: string] {
    if not (is-record $document) {
        fail $"($label) must be a JSON object"
    }
    let hook_map = ($document.hooks? | default {})
    if not (is-record $hook_map) {
        fail $"($label) hooks must be a JSON object"
    }
    for event in ($hook_map | columns) {
        let groups = ($hook_map | get $event)
        if not (is-list $groups) {
            fail $"($label) hook event ($event) must contain a list of matcher groups"
        }
        for group in $groups {
            if not (is-record $group) {
                fail $"($label) hook event ($event) contains a non-object matcher group"
            }
            let handlers = ($group.hooks? | default null)
            if not (is-list $handlers) {
                fail $"($label) hook event ($event) matcher group must contain a hooks list"
            }
            if ($handlers | any {|handler| not (is-record $handler) }) {
                fail $"($label) hook event ($event) contains a non-object handler"
            }
        }
    }
}

def strip-owned-hook-groups [groups] {
    $groups
    | each {|group|
        let handlers = ($group.hooks | where {|handler|
            let command = ($handler.command? | default "")
            not (($command in $OWNED_HOOK_COMMANDS) and ($command not-in $PRESERVED_OPTIONAL_HOOK_COMMANDS))
        })
        if ($handlers | is-empty) {
            null
        } else {
            $group | upsert hooks $handlers
        }
    }
    | compact
}

def merge-hook-document [prior, reviewed, generated_description: string] {
    validate-hook-document $prior "existing hooks output"
    let prior_hook_map = ($prior.hooks? | default {})
    mut merged_hook_map = {}
    for event in ($prior_hook_map | columns) {
        let retained = (strip-owned-hook-groups ($prior_hook_map | get $event))
        if not ($retained | is-empty) {
            $merged_hook_map = ($merged_hook_map | upsert $event $retained)
        }
    }
    for event in ($reviewed.hooks | columns) {
        let retained = ($merged_hook_map | get --optional $event | default [])
        let reviewed_groups = ($reviewed.hooks | get $event)
        $merged_hook_map = ($merged_hook_map | upsert $event ($retained | append $reviewed_groups))
    }
    let metadata_keys = ($prior | columns | where {|key| $key not-in ["description" "hooks"] })
    let metadata = if ($metadata_keys | is-empty) {
        {}
    } else {
        $prior | select ...$metadata_keys
    }
    $metadata | merge {description: $generated_description, hooks: $merged_hook_map}
}

def main [
    config_src: path
    config_out: path
    rules_src: path
    rules_out: path
    hooks_src: path
    hooks_out: path
    --recover-only
] {
    let outputs = [$config_out $rules_out $hooks_out]
    let expanded_outputs = ($outputs | each {|output| $output | path expand })
    if ($expanded_outputs | uniq | length) != ($outputs | length) {
        fail "config, rules, and hooks outputs must be different files"
    }
    for output in $outputs {
        if ($output | path exists) and (($output | path type) == "dir") {
            fail $"output path is a directory: ($output)"
        }
    }
    let config_dir = ($config_out | path dirname | path expand)
    let rules_dir = ($rules_out | path dirname | path expand)
    let hooks_dir = ($hooks_out | path dirname | path expand)
    if ($config_dir != $rules_dir) or ($config_dir != $hooks_dir) {
        fail "config, rules, and hooks outputs must share one directory for coordinated publication"
    }
    mkdir $config_dir
    let journal = ($config_dir | path join $TRANSACTION_JOURNAL)
    let recovered = (recover-transaction $journal $config_out $rules_out $hooks_out)
    if $recover_only {
        if not $recovered { print "no pending Codex config/rules/hooks transaction" }
        return
    }

    if not ($config_src | path exists) {
        fail $"config input not found: ($config_src)"
    }
    if not ($rules_src | path exists) {
        fail $"rules input not found: ($rules_src)"
    }
    if not ($hooks_src | path exists) {
        fail $"hooks input not found: ($hooks_src)"
    }

    let config_raw = (open --raw $config_src)
    let config_declared = (try { $config_raw | from toml } catch {
        fail $"config input is not valid TOML: ($config_src)"
    })
    let retired_home_tree = (["." "local"] | str join)
    let forbidden_paths = ($FORBIDDEN_PATHS | append $retired_home_tree)
    for pattern in $forbidden_paths {
        if ($config_raw | str contains $pattern) {
            fail $"config input references forbidden path ($pattern): ($config_src)"
        }
    }
    let icm_command = ($config_declared.mcp_servers?.icm?.command? | default "")
    if $icm_command != $PROFILE_ICM {
        fail $"reviewed ICM command must be the exact profile selector ($PROFILE_ICM)"
    }

    let rules_raw = (open --raw $rules_src)
    if not ($rules_raw | str starts-with "# FlexNetOS Codex Durable Rules\n") {
        fail $"rules input must start with the durable rules heading: ($rules_src)"
    }
    if ($rules_raw | str contains $RULES_GENERATED_MARKER) {
        fail $"rules input contains a generated-output marker: ($rules_src)"
    }

    let hooks_raw = (open --raw $hooks_src)
    let hooks_declared = (try { $hooks_raw | from json } catch {
        fail $"hooks input is not valid JSON: ($hooks_src)"
    })
    validate-hook-document $hooks_declared "reviewed hooks input"
    let hooks_columns = ($hooks_declared | columns | sort)
    if $hooks_columns != ["description" "hooks"] {
        fail $"hooks input must contain only description and hooks: ($hooks_src)"
    }
    if (($hooks_declared.description? | describe) != "string") {
        fail $"hooks input description must be a string: ($hooks_src)"
    }
    if ($hooks_raw | str contains $HOOKS_GENERATED_MARKER) {
        fail $"hooks input contains a generated-output marker: ($hooks_src)"
    }
    if $hooks_declared.hooks != $REQUIRED_HOOKS {
        fail $"hooks input does not match the reviewed RTK and ICM lifecycle contract: ($hooks_src)"
    }
    for pattern in $forbidden_paths {
        if ($hooks_raw | str contains $pattern) {
            fail $"hooks input references forbidden path ($pattern): ($hooks_src)"
        }
    }

    let prior_hooks = if ($hooks_out | path exists) {
        let prior_raw = (open --raw $hooks_out)
        try { $prior_raw | from json } catch {
            fail $"existing hooks output is not valid JSON: ($hooks_out)"
        }
    } else { {} }
    let hooks_hash = ($hooks_raw | hash sha256)
    let hooks_description = (
        $"($HOOKS_GENERATED_MARKER); authorship input: ($CANONICAL_HOOKS_INPUT); source_sha256 = ($hooks_hash); review required through /hooks."
    )
    let merged_hooks = (merge-hook-document $prior_hooks $hooks_declared $hooks_description)
    let merged_hooks_raw = (($merged_hooks | to json --indent 2) + "\n")
    for pattern in $forbidden_paths {
        if ($merged_hooks_raw | str contains $pattern) {
            fail $"materialized hooks would retain forbidden path ($pattern): ($hooks_out)"
        }
    }

    # The reviewed source owns every top-level key/table that it declares.
    # Live-only top-level tables are runtime state and survive a cutover. This
    # keeps Codex-managed hook trust state without allowing a stale live table
    # (for example projects or MCP servers) to override its reviewed owner.
    let prior_config = if ($config_out | path exists) {
        let prior_raw = (open --raw $config_out)
        try { $prior_raw | from toml } catch {
            fail $"existing config output is not valid TOML: ($config_out)"
        }
    } else { {} }
    let source_keys = ($config_declared | columns)
    let prior_keys = ($prior_config | columns)
    let replaced_keys = ($source_keys | where {|key| $key in $prior_keys })
    let runtime_projection = if ($replaced_keys | is-empty) {
        $prior_config
    } else {
        $prior_config | reject ...$replaced_keys
    }
    let runtime_projection_raw = ($runtime_projection | to toml)
    let runtime_projection_hash = ($runtime_projection_raw | hash sha256)
    let merged_config = ($runtime_projection | merge $config_declared)
    let merged_config_raw = ($merged_config | to toml)
    for pattern in $forbidden_paths {
        if ($merged_config_raw | str contains $pattern) {
            fail $"materialized config would retain forbidden path ($pattern): ($config_out)"
        }
    }

    let config_hash = ($config_raw | hash sha256)
    let rules_hash = ($rules_raw | hash sha256)
    let config_header = [
        $"# ($CONFIG_GENERATED_MARKER) — do not hand-edit."
        $"# authorship input: ($CANONICAL_CONFIG_INPUT)"
        $"# source_sha256 = ($config_hash)"
        $"# runtime_projection_sha256 = ($runtime_projection_hash)"
        ""
    ]
    let rules_header = [
        $"<!-- ($RULES_GENERATED_MARKER) — do not hand-edit. -->"
        $"<!-- authorship input: ($CANONICAL_RULES_INPUT) -->"
        $"<!-- source_sha256 = ($rules_hash) -->"
        ""
    ]

    let token = (random uuid)
    let paths = (transaction-paths $config_dir $token)
    let config_stage = $paths.config_stage
    let rules_stage = $paths.rules_stage
    let hooks_stage = $paths.hooks_stage
    let config_backup = $paths.config_backup
    let rules_backup = $paths.rules_backup
    let hooks_backup = $paths.hooks_backup
    let config_rendered = (($config_header | str join "\n") + $merged_config_raw)
    let rules_rendered = (($rules_header | str join "\n") + $rules_raw)
    let hooks_rendered = $merged_hooks_raw
    let had_config = ($config_out | path exists)
    let had_rules = ($rules_out | path exists)
    let had_hooks = ($hooks_out | path exists)
    let transaction = {
        schema: $TRANSACTION_SCHEMA
        token: $token
        config_name: ($config_out | path basename)
        rules_name: ($rules_out | path basename)
        hooks_name: ($hooks_out | path basename)
        had_config: $had_config
        had_rules: $had_rules
        had_hooks: $had_hooks
    }
    try {
        $transaction | to json --indent 2 | save --raw $journal
    } catch {|error|
        fail $"unable to write transaction journal: ($error.msg)"
    }
    let journal_sync = (do { ^sync -f $config_dir } | complete)
    if $journal_sync.exit_code != 0 {
        remove-if-present $journal
        fail $"unable to persist transaction journal: ($journal_sync.stderr | str trim)"
    }

    # Prepare all complete files before changing any live output. A staging
    # failure therefore leaves the previous generation byte-for-byte intact.
    try {
        $config_rendered | save --raw $config_stage
        $rules_rendered | save --raw $rules_stage
        $hooks_rendered | save --raw $hooks_stage
    } catch {|error|
        remove-transaction-artifacts $paths
        remove-if-present $journal
        fail $"unable to stage output set: ($error.msg)"
    }
    for staged in [$config_stage $rules_stage $hooks_stage] {
        let mode = (do { ^chmod 0644 $staged } | complete)
        if $mode.exit_code != 0 {
            remove-transaction-artifacts $paths
            remove-if-present $journal
            fail $"unable to set generated output mode 0644: ($staged)"
        }
        let staged_sync = (do { ^sync -f $staged } | complete)
        if $staged_sync.exit_code != 0 {
            remove-transaction-artifacts $paths
            remove-if-present $journal
            fail $"unable to persist staged output: ($staged_sync.stderr | str trim)"
        }
    }

    try {
        if $had_config { cp $config_out $config_backup }
        if $had_rules { cp $rules_out $rules_backup }
        if $had_hooks { cp $hooks_out $hooks_backup }
    } catch {|error|
        remove-transaction-artifacts $paths
        remove-if-present $journal
        fail $"unable to stage rollback copies: ($error.msg)"
    }
    for backup in [$config_backup $rules_backup $hooks_backup] {
        if ($backup | path exists) {
            let backup_sync = (do { ^sync -f $backup } | complete)
            if $backup_sync.exit_code != 0 {
                remove-transaction-artifacts $paths
                remove-if-present $journal
                fail $"unable to persist rollback copy: ($backup_sync.stderr | str trim)"
            }
        }
    }

    try {
        mv --force $config_stage $config_out
    } catch {|error|
        recover-transaction $journal $config_out $rules_out $hooks_out | ignore
        fail $"unable to replace config output: ($error.msg)"
    }
    if (($env.YAZELIX_TEST_CRASH_AFTER_CONFIG_REPLACE? | default "") == "1") {
        print --stderr "codex config materializer: injected interruption after config replacement"
        exit 86
    }
    # POSIX cannot publish three independent pathnames with one rename. Keep the
    # contract honest: publication uses a durable recovery journal and rollback
    # copies, but is not described as a three-path atomic rename.
    try {
        mv --force $rules_stage $rules_out
    } catch {|error|
        recover-transaction $journal $config_out $rules_out $hooks_out | ignore
        fail $"unable to replace rules output; config was rolled back: ($error.msg)"
    }
    if (($env.YAZELIX_TEST_CRASH_AFTER_RULES_REPLACE? | default "") == "1") {
        print --stderr "codex config materializer: injected interruption after rules replacement"
        exit 87
    }
    try {
        mv --force $hooks_stage $hooks_out
    } catch {|error|
        recover-transaction $journal $config_out $rules_out $hooks_out | ignore
        fail $"unable to replace hooks output; config and rules were rolled back: ($error.msg)"
    }
    if (($env.YAZELIX_TEST_CRASH_AFTER_HOOKS_REPLACE? | default "") == "1") {
        print --stderr "codex config materializer: injected interruption after hooks replacement"
        exit 88
    }
    let output_sync = (do { ^sync -f $config_dir } | complete)
    if $output_sync.exit_code != 0 {
        fail $"unable to persist generated output set: ($output_sync.stderr | str trim)"
    }
    remove-if-present $journal
    do { ^sync -f $config_dir } | complete | ignore
    remove-transaction-artifacts $paths

    print $"ok materialized ($config_out) source_sha256=($config_hash)"
    print $"ok materialized ($rules_out) source_sha256=($rules_hash)"
    print $"ok materialized ($hooks_out) source_sha256=($hooks_hash)"
}
